### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by BodaThomas** [mrlizzard/Epitech-HEADER-2018#3]
1. J'appuie une première fois sur le raccourcis CTRL-SHIFT-H, le bug apparaît
2. J'appuie une seconde fois, le package fonctionne

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: "Fedora release
**Thrown From**: [epitech-header-2018](https://github.com/mrlizzard/Epitech-HEADER-2018) package 4.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /home/tboda/.atom/packages/epitech-header-2018/lib/epitech-header.coffee:57

TypeError: Cannot read property 'file' of undefined
    at Object.insert (/packages/epitech-header-2018/lib/epitech-header.coffee:57:42)
    at /packages/epitech-header-2018/lib/epitech-header.coffee:22:93)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -6:24.3.0 core:move-up (input.hidden-input)
     -6:23.9.0 core:move-down (input.hidden-input)
     -6:23.3.0 core:move-right (input.hidden-input)
     -6:22.8.0 core:move-up (input.hidden-input)
  4x -6:22.3.0 core:move-right (input.hidden-input)
     -6:18 core:move-up (input.hidden-input)
  2x -6:17.3.0 core:move-down (input.hidden-input)
     -5:58.6.0 core:move-up (input.hidden-input)
  4x -5:57.8.0 core:move-left (input.hidden-input)
  8x -5:53.4.0 core:move-right (input.hidden-input)
     -3:15.9.0 core:save (input.hidden-input)
  4x -2:26.7.0 core:backspace (input.hidden-input)
     -2:25.3.0 core:save (input.hidden-input)
  4x -2:04.9.0 core:backspace (input.hidden-input)
     -1:57.2.0 core:save (input.hidden-input)
  2x -0:05.7.0 epitech-header:insert (div.tool-panel.tree-view)
```

### Non-Core Packages

```
epitech-header-2018 4.0.2 
```

**Comment by cyrilcolinet** [comment]
Salut @MrToto54,

Peux-tu me donner plus de précisions ?
Lorsque tu exécute le la combinaison de touches (<kbd>(CTRL+SHIFT-H)</kbd>), as-tu le fichier ouvert ?

**EDIT:** J'ai réussi à reproduire le BUG, le problème est que, lorsque que tu clique sur un fichier dans l'arbre du projet (voir ci-dessous), et que tu essaie d'y appliquer un header, ça ne marche pas.

![image](https://user-images.githubusercontent.com/8271271/46530525-55837f00-c89a-11e8-9d55-165e6a5bec6d.png)

J'applique un gros fix général dans la journée, merci du report.
Bonne pisicne :wink:

**Comment by BodaThomas** [comment]
Salut! 

Alors oui le fichier était ouvert, mais je n’étais pas dedans. Mon curseur ne clignotait pas, j’ai oublié de cliquer dessus. Excuse-moi pour la gêne occasionnée.

**Comment by BodaThomas** [comment]
> Salut @MrToto54,
> 
> Peux-tu me donner plus de précisions ?
> Lorsque tu exécute le la combinaison de touches ((CTRL+SHIFT-H)), as-tu le fichier ouvert ?
> 
> **EDIT:** J'ai réussi à reproduire le BUG, le problème est que, lorsque que tu clique sur un fichier dans l'arbre du projet (voir ci-dessous), et que tu essaie d'y appliquer un header, ça ne marche pas.
> 
> ![image](https://user-images.githubusercontent.com/8271271/46530525-55837f00-c89a-11e8-9d55-165e6a5bec6d.png)
> 
> J'applique un gros fix général dans la journée, merci du report.
> Bonne pisicne

Dac, super !
Cependant je n'ai pas eu de mises à jour sur Atom. C'est normal ?

**Comment by cyrilcolinet** [comment]
> Dac, super !
> Cependant je n'ai pas eu de mises à jour sur Atom. C'est normal ?

Salut @MrToto54, je n'ai pas encore eu le temps de mettre à jour...
Je profite en plus d'y ajouter plus des choses en plus ;)

**Comment by BodaThomas** [comment]
Salut !
Je viens aux nouvelles concernant le déploiement de la nouvelle mise à jour ;)
Sais-tu quand la nouvelle MAJ sera dispo ?

**Comment by cyrilcolinet** [comment]
Salut @MrToto54,

Je n'ai pas encore eu tout à fait le temps d'avancer dessus depuis un moment malheureusement...
Comme je suis en stage en ce moment, et que c'est bientôt la fin pour moi, le temps libre est plutôt consacré a autre chose que du code.

Mais ne t'inquiète pas, une annonce sera faite lors de la mise à jour, et atom te proposera directement de faire cette mise à jour.

En te souhaitant une bonne soirée.
